"""Restore a same-branch research journal; missing history never silently resets it.

GitHub artifacts are a continuity checkpoint, not a durable trading runtime.
This helper has no broker or execution imports and uses only read-only Actions APIs.
"""
from __future__ import annotations

import argparse
import hashlib
from datetime import date, datetime
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import zipfile

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from research.shadow.journal import append_event, load_events, verify_file
from research.data_ingest.yahoo_chart_daily import completed_us_session

MAX_JOURNAL_BYTES = 32 * 1024 * 1024


class CheckpointError(ValueError):
    pass


def api_pages(endpoint: str) -> list[dict]:
    result = subprocess.run(
        ["gh", "api", "--paginate", "--slurp", endpoint],
        check=True, capture_output=True, text=True, timeout=120,
    )
    pages = json.loads(result.stdout)
    if not isinstance(pages, list) or not all(isinstance(p, dict) for p in pages):
        raise CheckpointError("invalid Actions pagination response")
    return pages


def select_run(pages: list[dict], branch: str, current_run: int, event: str) -> dict | None:
    # A fork PR named 'main' must never supply the production main checkpoint.
    events = {"pull_request"} if event == "pull_request" else {"push", "schedule", "workflow_dispatch"}
    candidates = [
        run for page in pages for run in page["workflow_runs"]
        if run["head_branch"] == branch and run["id"] != current_run
        and run["event"] in events and run["conclusion"] == "success"
    ]
    return max(candidates, key=lambda r: r["id"], default=None)


def select_artifact(pages: list[dict]) -> dict:
    matches = [a for p in pages for a in p["artifacts"]
               if a["name"] == "trips-historical-evidence"]
    if len(matches) != 1 or matches[0].get("expired", True):
        raise CheckpointError("prior checkpoint missing or expired; refusing a new chain")
    return matches[0]


def restore_archive(archive_path: Path, destination: Path) -> dict:
    target = destination / "journal.jsonl"
    if target.exists():
        raise CheckpointError("refusing to overwrite an existing journal")
    # Never extract arbitrary paths or metadata from the artifact. Reports and heartbeat
    # are regenerated by the runner; only the verified journal is carried forward.
    with zipfile.ZipFile(archive_path) as archive:
        entries = [i for i in archive.infolist() if i.filename == "shadow/journal.jsonl"]
        if len(entries) != 1:
            raise CheckpointError("prior artifact has no unique journal; refusing a new chain")
        entry = entries[0]
        if entry.file_size <= 0 or entry.file_size > MAX_JOURNAL_BYTES:
            raise CheckpointError("journal empty or exceeds checkpoint size limit")
        content = archive.read(entry)
    destination.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=destination) as temp:
        staged = Path(temp) / "journal.jsonl"
        staged.write_bytes(content)
        chain = verify_file(staged)
        if not chain["valid"] or chain["count"] == 0:
            raise CheckpointError("checkpoint journal hash chain is invalid")
        events = load_events(staged)
        first_unclosed = None
        for index, event in enumerate(events):
            day_text = event.get("execution_market_date") or event.get("market_date")
            if event.get("kind") in {"STATE", "DECISION", "HYPOTHETICAL_REBALANCE"} and day_text:
                market_day = date.fromisoformat(day_text)
                attempted = datetime.fromisoformat(event["attempted_at"].replace("Z", "+00:00"))
                if not completed_us_session(market_day, attempted):
                    first_unclosed = index
                    break
        if first_unclosed is not None:
            # Keep every original event in the recovered audit trail, but do not let
            # an unclosed session remain a STATE used by the runner/report. This is
            # a research-data recovery, never an owner-authorization operation.
            prefix = events[:first_unclosed]
            if not any(e.get("kind") == "STATE" for e in prefix):
                raise CheckpointError("no completed state before unclosed session; refusing a new chain")
            staged.write_text("".join(json.dumps(e, sort_keys=True, separators=(",", ":")) + "\n"
                                      for e in prefix), encoding="utf-8")
            archive_hash = hashlib.sha256(archive_path.read_bytes()).hexdigest()
            for original in events[first_unclosed:]:
                append_event(staged, {"kind": "QUARANTINED_EVENT", "reason": "UNCLOSED_US_SESSION",
                                     "original_event": original, "source_archive_sha256": archive_hash,
                                     "execution_authority": "NONE"})
            chain = verify_file(staged)
            chain["quarantined_events"] = len(events) - first_unclosed
            chain["original_last_hash"] = events[-1]["event_hash"]
        staged.replace(target)
    return chain


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--destination", type=Path, required=True)
    args = parser.parse_args()
    try:
        repo = os.environ["GITHUB_REPOSITORY"]
        if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repo):
            raise CheckpointError("invalid repository")
        branch = os.environ.get("GITHUB_HEAD_REF") or os.environ["GITHUB_REF_NAME"]
        event = os.environ["GITHUB_EVENT_NAME"]
        current = int(os.environ["GITHUB_RUN_ID"])
        pages = api_pages(f"repos/{repo}/actions/workflows/research-market-data.yml/runs?status=success&per_page=100")
        run = select_run(pages, branch, current, event)
        if run is None:
            if branch == "main" and event != "pull_request":
                raise CheckpointError("main has no recoverable prior run; owner investigation required")
            print(json.dumps({"status": "NEW_RESEARCH_BRANCH", "branch": branch}))
            return 0
        artifact = select_artifact(api_pages(f"repos/{repo}/actions/runs/{run['id']}/artifacts?per_page=100"))
        with tempfile.TemporaryDirectory() as temp:
            archive = Path(temp) / "checkpoint.zip"
            with archive.open("wb") as output:
                subprocess.run(["gh", "api", f"repos/{repo}/actions/artifacts/{int(artifact['id'])}/zip"],
                               stdout=output, check=True, timeout=120)
            chain = restore_archive(archive, args.destination)
        print(json.dumps({"status": "RESTORED", "branch": branch,
                          "source_run": run["id"], "artifact_id": artifact["id"], "chain": chain}, sort_keys=True))
        return 0
    except (CheckpointError, KeyError, ValueError, OSError, subprocess.SubprocessError, zipfile.BadZipFile) as exc:
        print(f"checkpoint restore failed closed: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
